# Generated by Django 5.2.8 on 2026-02-24 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ROADS', 'Roads & Infrastructure'), ('TRAFFIC', 'Traffic & Road Safety'), ('WATER', 'Water Supply'), ('SEWERAGE', 'Sewerage & Drainage'), ('SANITATION', 'Sanitation & Garbage'), ('LIGHTING', 'Street Lighting'), ('PARKS', 'Parks & Public Spaces'), ('ANIMALS', 'Stray Animals'), ('ILLEGAL_CONSTRUCTION', 'Illegal Construction'), ('ENCROACHMENT', 'Encroachment'), ('PROPERTY_DAMAGE', 'Public Property Damage'), ('ELECTRICITY', 'Electricity & Power Issues'), ('OTHER', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL)),
                ('officers', models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
