# Generated by Django 5.2.8 on 2026-02-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='contact_phone',
        ),
    ]
