# Generated by Django 5.2.8 on 2026-02-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_department_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='officers',
        ),
    ]
