# Generated by Django 5.2.8 on 2026-02-24 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_remove_department_officers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='contact_phone',
            field=models.CharField(default=10, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='officers',
            field=models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
