# Generated by Django 5.2.8 on 2026-02-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_department_contact_phone_department_officers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
