# Generated by Django 5.2.8 on 2026-03-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_alter_department_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_officers', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('ANIMALS', 'Animals'), ('PARKS', 'Parks'), ('LIGHTING', 'Lighting'), ('STATION', 'Station'), ('SEWERAGE', 'Sewerage'), ('WATER', 'Water'), ('TRAFFIC', 'Traffic'), ('ROADS', 'Roads'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
