# Generated by Django 5.2.8 on 2026-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_department_list_and_officer_dept_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('ROADS', 'Roads & Infrastructure'), ('TRAFFIC', 'Traffic & Road Safety'), ('WATER', 'Water Supply'), ('SEWERAGE', 'Sewerage & Drainage'), ('SANITATION', 'Sanitation & Garbage'), ('LIGHTING', 'Street Lighting'), ('HEALTH', 'Public Health Hazard'), ('PARKS', 'Parks & Public Spaces'), ('ANIMALS', 'Stray Animals'), ('ILLEGAL_CONSTRUCTION', 'Illegal Construction'), ('ENCROACHMENT', 'Encroachment'), ('PROPERTY_DAMAGE', 'Public Property Damage'), ('NOISE', 'Noise Pollution'), ('ELECTRICITY', 'Electricity & Power Issues'), ('VENDORS', 'Street Vendor / Hawker Issues'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
