# Generated by Django 6.0.3 on 2026-03-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0009_alter_officer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
