# Generated by Django 6.0.2 on 2026-02-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('general', 'general'), ('complaint', 'complaint'), ('feedback', 'feedback')], max_length=20)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
