# Generated by Django 6.0.2 on 2026-03-22 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0004_alter_category_department'),
        ('departments', '0006_alter_department_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=300)),
                ('image_video', models.FileField(blank=True, null=True, upload_to='media/')),
                ('location_address', models.CharField(max_length=200)),
                ('location_District', models.CharField(max_length=100)),
                ('location_taluk', models.CharField(max_length=100)),
                ('priority_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='Pending', max_length=20)),
                ('current_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_assignd', models.BooleanField(default=False)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='Categories.category')),
                ('officer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='departments.officer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='complaints.complaint')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_assignments', to='departments.officer')),
            ],
            options={
                'unique_together': {('complaint', 'officer')},
            },
        ),
    ]
