# Generated by Django 6.0.2 on 2026-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image_video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
