# Generated by Django 6.0.2 on 2026-04-04 12:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_update_complaint_image_video_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
