# Generated by Django 5.2.8 on 2026-03-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0002_populate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
