# Generated by Django 5.2.8 on 2026-03-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_alter_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
