# Generated by Django 5.2.8 on 2026-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0004_alter_category_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
