# Generated by Django 5.2.8 on 2026-03-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='User_Role',
            field=models.CharField(choices=[('Civic-User', 'Civic-User'), ('Department-User', 'Department-User'), ('Officer', 'Officer'), ('Admin-User', 'Admin-User')], max_length=200),
        ),
    ]
