# Generated by Django 6.0.2 on 2026-04-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_verified_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('user_role', models.CharField(choices=[('Civic-User', 'Civic-User'), ('Department-User', 'Department-User'), ('Officer', 'Officer'), ('Admin-User', 'Admin-User')], default='Civic-User', max_length=200)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='accounts_pe_email_1e1edb_idx'), models.Index(fields=['created_at'], name='accounts_pe_created_df5517_idx')],
            },
        ),
    ]
